version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: batalj-mongodb-dev
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data_dev:/data/db
    environment:
      - MONGO_INITDB_DATABASE=batalj
    networks:
      - batalj-network

networks:
  batalj-network:
    driver: bridge
